enabled: True

redis_port: 6379
redis_host: localhost
redis_prefix: sxp
redis_db: 15

metrics: false
statsd_url: 'udp://localhost:8125/sixpack'


robot_regex: $^|trivial|facebook|MetaURI|butterfly|google|amazon|goldfire|sleuth|xenu|msnbot|SiteUptime|Slurp|WordPress|ZIBB|ZyBorg|pingdom|bot|yahoo|slurp|java|fetch|spider|url|crawl|oneriot|abby|commentreader|twiceler
ignored_ip_addresses: []

asset_path: gen
secret_key: '<your secret key here>'
